version: '3'

services:
  cups-airprint:
    build: .
    container_name: cups-airprint
    restart: unless-stopped
    ports:
      - "631:631/tcp"    # CUPS Web界面和打印服务
      - "5353:5353/udp"  # Avahi/Bonjour服务发现
    volumes:
      - ./config:/etc/cups  # CUPS配置持久化
      - ./spool:/var/spool/cups  # 打印队列持久化
    devices:
      - /dev/bus/usb:/dev/bus/usb  # USB设备直通
    environment:
      - TZ=Asia/Shanghai  # 时区设置
    # 确保网络托管模式支持mDNS(Bonjour)
    network_mode: "host"  # 使用host网络模式以支持mDNS广播
    privileged: true  # 需要特权模式才能访问USB设备
    # 添加健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:631"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 